a = input('Digite Algo: ')
print('O tipo primitivo desse valor é',type(a))
print ('Só tem espaços: ', a.isspace())
print ('Este valor é numérico? ', a.isnumeric())
print ('É alfabético? ', a.isalpha())
print ('è alfanumérico? ', a.isalnum())
print ('Esta em maiúsculas? ', a.isupper())
print ('Esta em minúsculas? ', a.islower())
print ('Esta capitalizada? ', a.istitle())
