nome = str(input('Digite seu nome: '))
mai = nome.upper()
minu = nome.lower()
qnts = len(nome)
prime = len(nome[0:6])
print('Nome: {}'.format(nome))
print('Seu nome com todas as letras maiúsculas:')
print('{}'.format(mai))
print('Seu nome com todas as letras minúsculas: ')
print('{}'.format(minu))
print('Seu nome tem exatamente {} letras'.format(qnts))
print('Seu primeiro nome tem {} letras'.format(prime))